### ISSUE TITLE
Backspace at beginning of unstyled after paragraph

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/slate-edit-list#36]
- [ ] Add test with following yaml
- [ ] Fix it

```yaml
type: list_item
nodes:
  - kind: block
     type: paragraph
     nodes:
        - kind: text
           text: Hello
  - kind: block
     type: unstyled
     nodes:
        - kind: text
           text: <cursor>World
```
